#!/bin/bash

#
# save current variables
#
cur_dir=`pwd`
cur_path=$PATH
cur_include_path=$C_INCLUDE_PATH
cur_library_path=$LIBRARY_PATH
cur_cflags=$CFLAGS
cur_ldflags=$LDFLAGS

# everything is built in "build" and installed to "stage" so it doesn't clutter up your system

# necessary environment variables
#export ROOT_DIR=${ROOT_DIR:-`cd ..;pwd`}
export ROOT_DIR=${ROOT_DIR:-`pwd`}
export CODEC_DIR=${CODEC_DIR:-${ROOT_DIR}/codecs}
export FAAC_DIR=${FAAC_DIR:-${CODEC_DIR}/faac}
export FAAD2_DIR=${FAAD2_DIR:-${CODEC_DIR}/faad2}
export XVID_DIR=${XVID_DIR:-${CODEC_DIR}/xvidcore}
export X264_DIR=${X264_DIR:-${CODEC_DIR}/x264}
#export FFMPEG_DIR=${FFMPEG_DIR:-${ROOT_DIR}/mplayerhq/ffmpeg}
export FFMPEG_DIR=${FFMPEG_DIR:-${CODEC_DIR}/ffmpeg}

# where we'll stage everything
#export STAGE_DIR=${STAGE:-`pwd`/stage}
#export STAGE_BIN=${STAGE_BIN:-${STAGE_DIR}/bin}
#export STAGE_INC=${STAGE_INC:-${STAGE_DIR}/include}
#export STAGE_LIB=${STAGE_LIB:-${STAGE_DIR}/lib}

# temporary build path
export BUILD_DIR=${BUILD_DIR:-`pwd`/build}

# create install directory
install_dir=/sagebuild
if [ ! -d $install_dir ]; then
  mkdir $install_dir
fi

#
# set variables
#
export CFLAGS="-I$install_dir/include -L$install_dir/lib"
#export LDFLAGS="-L$install_dir/lib"
#export C_INCLUDE_PATH=$install_dir/include:$C_INCLUDE_PATH
#export LIBRARY_PATH=$install_dir/lib:$LIBRARY_PATH
export PATH=$install_dir/bin:$PATH

#
# yasm dependency
#
#cd $cur_dir/yasm-1.0.1
#make clean
#./configure --prefix=$install_dir
#make
#make install

#make clean
#make z
#if [ $? -eq 0 ] ; then
#  do stuff when make succeeds
#else
#  do stuff when make fails
#   echo Yasm failed
#   exit $?;
#fi

#
# libx264 dependency
#
#cd $cur_dir/x264-snapshot-20100801-2245
#make clean
#./configure --prefix=$install_dir
#make
#make install

#
# lame dependency
#
#cd $cur_dir/lame-3.98.4
#make clean
#./configure --prefix=$install_dir
#make
#make install

#
# faad dependency
#
#cd $cur_dir/faad2-2.7
#make clean
#./configure --prefix=$install_dir
#make
#make install

#
# faac dependency
# won't build
mkdir -p "${BUILD_DIR}/faac"
pushd "${BUILD_DIR}/faac"
  #pushd "$cur_dir/codecs/faac"
  make clean
  test -f Makefile || \
    "${FAAC_DIR}"/configure --prefix=$install_dir --enable-static --disable-shared --without-mp4v2 \
    || exit $?
  make
  make install
popd

#
# xvid dependency
#
#cd $cur_dir/xvidcore-1.2.2/build/generic
#make clean
#./configure --prefix=$install_dir
#make
#make install

#
# ffmpeg
#
mkdir -p "${BUILD_DIR}"/ffmpeg
pushd "${BUILD_DIR}"/ffmpeg

#  cd $cur_dir/ffmpeg-pure-airvideo
#  cd $cur_dir/ffmpeg-sage-7.0.13
#  cd $cur_dir/ffmpeg-sage-7.0.13-and-segmenter-2.2.5
  chmod +x "${FFMPEG_DIR}"/configure
  chmod +x "${FFMPEG_DIR}"/version.sh
#  make clean
#  "${FFMPEG_DIR}"/configure --prefix=$install_dir --arch=i686 --cpu=i686 --disable-mmx --enable-gpl --enable-libx264 --enable-static --disable-shared --enable-pthreads --enable-libmp3lame --enable-libfaad --disable-decoder=aac --extra-ldflags=-L$install_dir/lib
#  "${FFMPEG_DIR}"/configure --prefix=$install_dir --arch=i686 --cpu=i686 --enable-gpl --enable-libx264 --enable-static --disable-shared --enable-pthreads --enable-libmp3lame --enable-libfaad --enable-libfaac --extra-ldflags=-L$install_dir/lib
#  "${FFMPEG_DIR}"/configure --prefix=$install_dir --enable-gpl --enable-libx264 --enable-static --disable-shared --enable-pthreads --enable-libmp3lame --enable-libfaad --extra-ldflags=-L$install_dir/lib
#sage
#  "${FFMPEG_DIR}"/configure --disable-ffserver --disable-ffplay --enable-gpl --enable-pthreads --enable-nonfree --enable-libfaac --enable-libx264 --enable-libxvid --disable-devices --disable-bzlib --prefix=/sage/bin/mplayerhq-sage/libs/ --extra-cflags=-I/sage/bin/mplayerhq-sage/libs/include --extra-ldflags=-L/sage/bin/mplayerhq-sage/libs/lib --disable-demuxer=msnwc_tcp
#test -f config.mak || \
    "${FFMPEG_DIR}/configure" --prefix="${install_dir}" --disable-ffserver --disable-ffplay --enable-gpl --enable-pthreads --enable-nonfree --enable-libfaac --enable-libx264 --enable-libxvid --disable-devices --disable-bzlib --extra-cflags="-I${install_dir}/include" --extra-ldflags="-L${install_dir}/lib" --disable-demuxer=msnwc_tcp
#    || exit $?

#  --extra-cflags=-I/usr/local/include --extra-ldflags=-L/usr/local/lib
make || exit $?
make install

#  cp $install_dir/bin/ffmpeg $cur_dir/../bin/linux32
popd

#
# reset variables
#
LDFLAGS=$cur_ldflags
CFLAGS=$cur_cflags
LIBRARY_PATH=$cur_library_path
C_INCLUDE_PATH=$cur_include_path
PATH=$cur_path
cd $cur_dir
